#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "⏳ Running Backend Linting..."
npm run lint --prefix backend || exit 1

echo "⏳ Running Frontend Linting..."
npm run lint --prefix frontend || exit 1

echo "✅ All pre-commit checks passed!"
